version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: secure_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elastic123
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.authc.anonymous.username=anonymous
      - xpack.security.authc.anonymous.roles=superuser
    ports:
      - "9200:9200"
      - "9300:9300"
